# Generated by Django 4.0 on 2023-04-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('markdown_file', models.FileField(blank=True, null=True, upload_to='markdown/')),
                ('test_file', models.FileField(blank=True, null=True, upload_to='testing/')),
            ],
        ),
    ]
