# Generated by Django 4.2 on 2023-04-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('markdown_file_path', models.CharField(max_length=255)),
                ('test_files_path', models.CharField(max_length=255)),
            ],
        ),
    ]
